# The URL the site will be built for
base_url = "https://en.about.museum-digital.org"

theme = "museum-digital-theme-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The default language; used in feeds.
default_language = "en"

# When set to "true", the generated HTML files are minified.
minify_html = false

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
output_dir = "public"

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
site_name = "museum-digital"
default_og_image = "data/img/logo/mdlogo-code-1024px.png"
